### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/bitcoin-price-app#80]
# Meta

- [ ] There is no homepage!

- [ ] Your repo does not have web commit signing off enabled. **PLEASE ENABLE IT**
# Automation

- [ ] **Mark this to override & close this issue.**
